var userItems = [
    {
        'name': 'Frey',
        'items': [
            {'type': 'weapon','id': 1},
            {'type': 'weapon','id': 2},
            {'type': 'weapon','id': 3},
            {'type': 'weapon','id': 4},
            {'type': 'weapon','id': 5},
            {'type': 'weapon','id': 6},
            {'type': 'weapon','id': 7},
            {'type': 'eidolon','id': 7},
            {'type': 'eidolon','id': 8},
            {'type': 'eidolon','id': 9},
            {'type': 'eidolon','id': 10},
            {'type': 'eidolon','id': 11},
            {'type': 'eidolon','id': 12},
            {'type': 'eidolon','id': 13},
            {'type': 'eidolon','id': 14},
            {'type': 'upgrade','id': 1, 'count' :3},
            {'type': 'upgrade','id': 2, 'count' :2},
            {'type': 'upgrade','id': 3, 'count' :5},
            {'type': 'upgrade','id': 4, 'count' :6},
            {'type': 'upgrade','id': 5, 'count' :4},
            {'type': 'upgrade','id': 6, 'count' :7},
            {'type': 'upgrade','id': 7, 'count' :1},
            {'type': 'level','id': 1, 'count' :3},
            {'type': 'level','id': 2, 'count' :4},
            {'type': 'level','id': 3, 'count' :5},
        ]
    },
    {
        'name': 'Blinky55',
        'items': null,
    },
    {
        'name': 'Myralla',
        'items': [
            {'type': 'weapon','id': 1},
            {'type': 'weapon','id': 2},
            {'type': 'weapon','id': 3},
            {'type': 'weapon','id': 4},
            {'type': 'weapon','id': 5},
            {'type': 'weapon','id': 6},
            {'type': 'weapon','id': 7},
            {'type': 'eidolon','id': 7},
            {'type': 'eidolon','id': 8},
            {'type': 'eidolon','id': 9},
            {'type': 'eidolon','id': 10},
            {'type': 'eidolon','id': 11},
            {'type': 'eidolon','id': 12},
            {'type': 'eidolon','id': 13},
            {'type': 'eidolon','id': 14},
            {'type': 'upgrade','id': 1, 'count' :3},
            {'type': 'upgrade','id': 2, 'count' :2},
            {'type': 'upgrade','id': 3, 'count' :5},
            {'type': 'upgrade','id': 4, 'count' :6},
            {'type': 'upgrade','id': 5, 'count' :4},
            {'type': 'upgrade','id': 6, 'count' :7},
            {'type': 'upgrade','id': 7, 'count' :1},
            {'type': 'level','id': 1, 'count' :3},
            {'type': 'level','id': 2, 'count' :4},
            {'type': 'level','id': 3, 'count' :5},
        ]
    },

];

export {userItems}
